### ISSUE TITLE
Image to Image pretrained model

### ISSUE THREAD

**Issue by muhammad-ahmed-ghani** [CompVis/retrieval-augmented-diffusion-models#1]
Hi @jenuk this is awesome to see the RAG models coming. I just wanted to know that do you have any plans of releasing the **image-to-image** model or **Inpainting** models with image as an input like [Paint by example](https://arxiv.org/abs/2211.13227) ?

**Comment by jenuk** [comment]
Hey, I cannot comment on any planned further research. But Paint by example provides their model themselves: https://github.com/Fantasy-Studio/Paint-by-Example and also Stability AI has released an unclip/image-variation model that goes in a similar direction, you might be interested in that. And of course there are also the unconditioned original LDM inpainting model and the text-conditioned SD inpainting model. If you specifically want a retrieval based inpainting model, you may want to use this codebase here to train your own :) If your resources are limited you might want to look into the method from [ControlNet](https://arxiv.org/abs/2302.05543)
