### ISSUE TITLE
Several references fusion

### ISSUE THREAD

**Issue by zeanfa** [CompVis/retrieval-augmented-diffusion-models#5]
Could you please describe the process of several references injection into diffusion.
So you get `k` CLIP embeddings for input query, how do you fuse these `k` representations?

**Comment by zeanfa** [comment]
In case anybody is interested: `k` CLIP embeddings for `b` batches give `bkD` context vector, where `D` is CLIP embedding size=512.

This goes into spatial transformer and is projected into K and V each of shape `bkd`, where  `d` is inner dim.

`k` simply means the length of context phrase, if you have 1 reference, you will get 1 context token and so on.

**Comment by MaximClouser** [comment]
How are the CLIP embeddings for the text and images combined (in the case where we want to use both the query and KNNs as conditioning)? Are they just concatenated?

**Comment by ShuaiWang97** [comment]
> How are the CLIP embeddings for the text and images combined (in the case where we want to use both the query and KNNs as conditioning)? Are they just concatenated?

I think so, the text and retrieved image embedding just get concatenated as condition of diffusion model

**Comment by MaximClouser** [comment]
> > How are the CLIP embeddings for the text and images combined (in the case where we want to use both the query and KNNs as conditioning)? Are they just concatenated?
> 
> I think so, the text and retrieved image embedding just get concatenated as condition of diffusion model

Do you think there might be a more meaningful way of combining them before being passed to the UNetModel? I am curious about the `conditional_retrieval_encoder` [here](https://github.com/CompVis/retrieval-augmented-diffusion-models/blob/1017f2b51d43ff530f178c72c460bbba83316da6/rdm/models/diffusion/ddpm.py#L811). Or might this already be handled by the cross attention in the UNetModel?

**Comment by ShuaiWang97** [comment]
> > > How are the CLIP embeddings for the text and images combined (in the case where we want to use both the query and KNNs as conditioning)? Are they just concatenated?
> > 
> > 
> > I think so, the text and retrieved image embedding just get concatenated as condition of diffusion model
> 
> Do you think there might be a more meaningful way of combining them before being passed to the UNetModel? I am curious about the `conditional_retrieval_encoder` [here](https://github.com/CompVis/retrieval-augmented-diffusion-models/blob/1017f2b51d43ff530f178c72c460bbba83316da6/rdm/models/diffusion/ddpm.py#L811). Or might this already be handled by the cross attention in the UNetModel?

I think now the text and retrieved image embedding is  concat then indeed fused by cross-attention, like standard stable diffusion model conditioning.  I am not sure what does the `conditional_retrieval_encoder` supposed to do. Do you have any intuitions? 
![image](https://github.com/user-attachments/assets/3c0730b8-4726-4d0d-b1d9-03fa110b7475)

**Comment by MaximClouser** [comment]
> > > > How are the CLIP embeddings for the text and images combined (in the case where we want to use both the query and KNNs as conditioning)? Are they just concatenated?
> > > 
> > > 
> > > I think so, the text and retrieved image embedding just get concatenated as condition of diffusion model
> > 
> > 
> > Do you think there might be a more meaningful way of combining them before being passed to the UNetModel? I am curious about the `conditional_retrieval_encoder` [here](https://github.com/CompVis/retrieval-augmented-diffusion-models/blob/1017f2b51d43ff530f178c72c460bbba83316da6/rdm/models/diffusion/ddpm.py#L811). Or might this already be handled by the cross attention in the UNetModel?
> 
> I think now the text and retrieved image embedding is concat then indeed fused by cross-attention, like standard stable diffusion model conditioning. I am not sure what does the `conditional_retrieval_encoder` supposed to do. Do you have any intuitions? ![image](https://private-user-images.githubusercontent.com/54426844/372528278-3c0730b8-4726-4d0d-b1d9-03fa110b7475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTU5MTgsIm5iZiI6MTcyNzc5NTYxOCwicGF0aCI6Ii81NDQyNjg0NC8zNzI1MjgyNzgtM2MwNzMwYjgtNDcyNi00ZDBkLWIxZDktMDNmYTExMGI3NDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE1MTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYzU1MWQxNmFjYmU0YzA4YWM1MTA1MTkyOTgwOWVmN2NkZjMzZjUxYmE5NWM5NjE0NjAyNjZmMTdmOTllMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hBLvpO5I9eVXz9AnYaM80aLvMPp2zrA-mnScUR-r65Q)

Yes, that makes sense. I just wonder if something like the `conditional_retrieval_encoder` can be used to create a learned representation of the image/text CLIP embeddings instead of just concatenating them and what the effect would be on generation (if any) because the comment there says "...modulating the nns with the query", but this might be overkill so we just leave it to cross attention.
